# Site settings
title: Edinburgh SocieTea
email:
description:
baseurl:
url: "http://www.edinburghsocietea.co.uk"
twitter: edinburghsocietea
github: edinburghsocietea

# Build settings
permalink: pretty

highlighter: rouge

gems:
  - jekyll-redirect-from
  
collections:
  - events
